apiVersion: v1
kind: Service
metadata:
  name: {{ include "emulatorjs.fullname" . }}
  labels:
    {{- include "emulatorjs.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.managementPort }}
      targetPort: 3000
      protocol: TCP
      name: management
    - port: {{ .Values.service.webuiPort }}
      targetPort: 80
      protocol: TCP
      name: webui
  selector:
    {{- include "emulatorjs.selectorLabels" . | nindent 4 }}
